---
title: "Assignments"
slug: assignments
---

- [<i class="fas fa-calculator"></i> `Grade Calculator`](https://ryansafner.shinyapps.io/thought_grade_calculator/)

Use this tool to calculate your final course grade and predict what grades you would need on remaining assignments to obtain a desired course grade.

## Short Papers {-}

There will be two short papers on assigned topics. The first will be early in the semester, covering topics from the first several weeks. The second will cover topics from the remaining weeks. I am looking for 3-5 page papers that explore subjects prompted by questions that I will provide to you in advance. However, I also encourage you to take the less-trodden path and explore something unique and interesting to you.

## Term Paper {-}

Each of you will write a term paper tracing and critically discussing the intellectual history of an economic topic of your choice. This assignment will be scaffolded so that certain sections of the paper are due partway through the semester so that I can provide feedback for you to incorporate into the final draft. More information will be provided in class.

## Participation and Discussion {-}

Every week, we will have a discussion board thread on Blackboard. You will be expected to contribute to the discussion board at least twice in the week. Your weekly contribution will be graded out of 5 points. At the end of the semester, I will apply the *average* of your weekly participation grades to apply (40%) towards your final course grade. 

I am interested in your thoughts, reactions, comments, and questions about any of the material (lectures and/or readings). You do not need to write more than a paragraph. Anything more than that, including continuing to reply to each others’ thoughts, questions, or comments, (which I strongly hope you do!) is solely based on your own interest and curiosity. I will jump in to answer questions the group is stuck on, give my two cents, and stir the pot as needed. I strontly hope we still keep a conversation going and can learn from each other, that was always my goal, not to lecture at you! If you crave visual human contact, you can submit your comments/reactions in the form of a short video, and we can try that out! Though we might eventually need to move beyond Blackboard in that case. We’ll see how things go.

Rubric:

| Category | 3 Points | 2 Points | 1 Point | 0 points |
|----------|----------|----------|---------|----------|
| Quantity | More than 2 replies/started threads | 2 replies/started threads | 1 reply | 0 posts |
| Quality | Extremely thought provoking, demonstrates clear grappling with readings, adds to conversation | Provides a well-reasoned reply, suggests familiarity with readings, keeps conversation going | A simple reply, may make no reference to readings or ideas, makes further conversation difficult | No effort |

Recall, these are out of 5 points. Notice it is possible to get above 5 points for a truly remarkable week of contributions, but I give these sparingly.

At the end of the semester, I will drop your lowest participation score.

## Tournament Votes

Since we all missed out on the NCAA Basketball Tournament last spring, I have set up a tournament for "the most interesting person in the history of economics." Each era of economic thought (Classical, Neoclassical, Heterodox, Modern) will have its own "division", in which we will vote for the champion of each era (out of up to 8 thinkers), who will then go head to head against the champions of other divisions for the title. 

Once we complete an era, we will hold the votes in head-to-head matchups between economists. You will *occasionally* be asked to write up a short explanation behind your vote (1-3 sentences) between each pair. This will allow you to remember and place each thinker in the context of the history of economic thought.

Votes, and your explanations, will take place in the discussion board.