---
title: "1.3 — Ancient Writers — Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

We begin our first look at some of the earliest writings about economics. None of these writers was self-consciously “an economist” or saw themselves as writing “about econonomics,”^[We won't see anything like this until the 19^th^ century.] but it is pretty clear they occasionally touch on economic subjects.

While I have not assigned any Plato to you^[Mainly because it is not in our *Reader*!], you should familiarize yourself briefly with Plato's more famous claims and view of "the ideal State." 

A note of caution in reading Plato: Plato was the student of the famous Socrates (who did not write anything down), and he writes in dialogues, often between his Socrates character and other famous Greek contemporaries.

Aristotle - who was Plato's greatest student - writes often in opposition to Plato's views. Thus, it is useful to know what Aristotle is referring to. 


# Required Readings:

- <i class="fas fas fa-book"></i> Part I (Pre-classical Thought) Introduction, Aristotle, *Politics* & *Nicomachean Ethics* in Medema & Samuels (*Reader*)
- <i class="fas fas fa-book"></i> Ch.2 (Early Preclassical Economic Thought) in Landreth & Colander

Blaug unfortunately does not cover anything before mercantilism & the physiocrats.

# Recommended Readings:

The following Wikipedia entries can also provide more background on these writers and their famous works:

- [<i class="fab fa-wikipedia-w"></i> Plato](https://en.wikipedia.org/wiki/Plato)
- [<i class="fab fa-wikipedia-w"></i> Plato's *Republic*](https://en.wikipedia.org/wiki/Republic_(Plato))
- [<i class="fab fa-wikipedia-w"></i> Aristotle](https://en.wikipedia.org/wiki/Aristotle)
- [<i class="fab fa-wikipedia-w"></i> Aristotle's *Politics*](https://en.wikipedia.org/wiki/Politics_(Aristotle))

# Questions to Help Your Reading

- How much of these writings are meant to be normative vs. positive? 
- What economic concepts or principles can you find in these writings?
- What can we glean of Aristotle's method or methodology? How does he approach the subjects he writes about and get us to learn something from them?
- What is the State, according to Aristotle? What are its origins and purpose? What is the relationship between the State and an individual?
- What does Aristotle have to say about property? What about property held "in common" versus "private" property?
- What the role of "equality" or "reciprocality" in exchange?
- What is the purpose, origin, and nature of money?
- What aspects of "the art of wealth-getting" are "natural" and what are "unnatural?"