---
title: "3.2 — Marginal Productivity Theory — Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

*Wednesday, October 14, 2020*

# Required Readings:

- <i class="fas fas fa-book"></i> Ch.9 "The Transition to Neoclassical Economics: Marginal Analysis Extended" up to Profits and Interest (p.260) in Landreth & Colander
- <i class="fas fas fa-book"></i> Ch.11 "Marginal productivity and factor prices" in Blaug

# Recommended Readings:

The following Wikipedia entries can also provide more background:

- [<i class="fab fa-wikipedia-w"></i> Friedrich von Wieser](https://en.wikipedia.org/wiki/Friedrich_von_Wieser)
- [<i class="fab fa-wikipedia-w"></i> Eugen von Böhm-Bawerk](https://en.wikipedia.org/wiki/Eugen_von_Böhm-Bawerk)
- [<i class="fab fa-wikipedia-w"></i> John Bates Clark](https://en.wikipedia.org/wiki/John_Bates_Clark)
- [<i class="fab fa-wikipedia-w"></i> Phillip Wicksteed](https://en.wikipedia.org/wiki/Phillip_Wicksteed)
- [<i class="fab fa-wikipedia-w"></i> Francis Ysidro Edgeworth](https://en.wikipedia.org/wiki/Francis_Ysidro_Edgeworth)
- [<i class="fab fa-wikipedia-w"></i> Knut Wicksell](https://en.wikipedia.org/wiki/Knut_Wicksell)

# Questions to Help Your Reading

- How are the prices of factors of production (land, labor, capital, etc) determined?
- What is the problem of imputation?
- What is marginal (physical) product? What is average (physical) product?
- What are returns to scale? How are they different from economies of scale?
- How does the assumption of competitive markets affect the answer to many of these questions?
- What is “product exhaustion?”
- Is there a moral connation of factors of production being paid their marginal products?