---
title: "3.5 — Marshallian Economics II: Supply & Theory of the Firm — Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

*Monday, October 26, 2020*

# Required Readings:

- <i class="fas fas fa-book"></i> Finish Ch.10 "Alfred Marshall and Neoclassical Economics" in Landreth & Colander
- <i class="fas fas fa-book"></i> Ch.10 "Marshallian Economics: Cost and Supply" in Blaug

# Recommended Readings:

- [<i class="fas fas fa-book"></i> Marshall, Alfred, 1920 (1890), *Principles of Economics* (8th ed.)](https://www.econlib.org/library/Marshall/marP.html)

The following Wikipedia entries can also provide more background:

- [<i class="fab fa-wikipedia-w"></i> Alfred Marshall](https://en.wikipedia.org/wiki/Alfred_Marshall)
- [<i class="fab fa-wikipedia-w"></i> Tax incidence](https://en.wikipedia.org/wiki/Tax_incidence)
- [<i class="fab fa-wikipedia-w"></i> Long run and short run](https://en.wikipedia.org/wiki/Long_run_and_short_run)
- [<i class="fab fa-wikipedia-w"></i> Fixed cost](https://en.wikipedia.org/wiki/Fixed_cost)
- [<i class="fab fa-wikipedia-w"></i> Variable cost](https://en.wikipedia.org/wiki/Variable_cost)
- [<i class="fab fa-wikipedia-w"></i> Cost curve](https://en.wikipedia.org/wiki/Cost_curve)
- [<i class="fab fa-wikipedia-w"></i> Quasi-rent](https://en.wikipedia.org/wiki/Quasi-rent)
- [<i class="fab fa-wikipedia-w"></i> Economies of scale](https://en.wikipedia.org/wiki/Economies_of_scale)
- [<i class="fab fa-wikipedia-w"></i> Economies of scale in Marshall](https://en.wikipedia.org/wiki/Economies_of_scale#Economies_of_scale_in_Marshall)
- [<i class="fab fa-wikipedia-w"></i> Quantity Theory of Money (Cambridge Approach)](https://en.wikipedia.org/wiki/Quantity_theory_of_money#Cambridge_approach)

# Questions to Help Your Reading

- What are the four “periods” (or “runs”) according to Marshall? What is different about the supply curve in each?
- What do you recognize from your principles & intermediate microeconomics courses from Marshall?
- What is a “quasi-rent”? Why does it only exist in the short run?
- What is a constant-cost, increasing-cost, and decreasing-cost industry?
- What are interval vs. external economies of scale? What are the implications for competition vs. monopoly?
- How does Marshall’s view of money and the quantity theory differ from Fisher?