---
title: "1.2 — So What Exactly is Economics? — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Wednesday, August 19, 2020*

# Overview

Today we discuss some common themes we will encounter this semester, and take a broad philosophical approach to what economics is and how it has developed.

# Readings

Please see [today's recommended readings](/reading/1.2-reading).

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/1.2-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/1.2-slides.pdf)

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 3:25 PM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).

# Assignments

We will start getting the discussion board up and running by the end of the week on Blackboard. 