---
title: "1.6 — Politics & Revolution — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Wednesday, September 2, 2020*

# Overview

Today we discuss Hobbes and Locke.

# Readings

Please see [today's recommended readings](/reading/1.6-reading).

As a historical aside: Here's a good clip setting the tension between King and Parliament at the start of the Civil Wars. King Charles I storms the House of Commons (Jan 4, 1629)^[By the way, because of this historic event, the only person in the world never allowed in the House of Commons is Queen Elizabeth II (whomever the current monarch is)!] in the 1970 movie *Cromwell*:^[And yes, that's Obi-Wan Kenobi as King Charles and the original Dumbledore as Oliver Cromwell.]

<iframe width="560" height="315" src="https://www.youtube.com/embed/wDsAn_u70tw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/1.6-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/1.6-slides.pdf)

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 3:25 PM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).

# Assignments

We will start getting the discussion board up and running by the end of the week on Blackboard. 