---
title: "2.6 — Classical Macroeconomics & The Great Debate Over Say’s Law — Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

*Monday, September 28, 2020*

# Overview

Today we begin by wrapping up Ricardo’s distribution theory, and turn to the first great debate in the history of economics: the (macroeconomic) debate between Ricardo and Malthus over “general gluts” and Say’s law

# Readings

Please see [today's recommended readings](/reading/2.6-reading).

# Slides

- [<i class="fas fa-chalkboard-teacher"></i> View Lecture Slides](/slides/2.6-slides.html)
- [<i class="fas fa-file-pdf"></i> Download as PDF](/slides/2.6-slides.pdf)

# Live Class Session on Zoom

The live class <i class="fas fa-video"></i> Zoom meeting link can be found on Blackboard (see `LIVE ZOOM MEETINGS` on the left navigation menu), starting at 3:25 PM.

If you are unable to join today's live session, or if you want to review, you can find the recording stored on Blackboard via Panopto (see `Class Recordings` on the left navigation menu).

# Assignments

Vote in the “Most Interesting Economist in History” Tournament, pre-Classical division, on Blackboard ASAP!