---
title: "Short Paper 1"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
```

- *Due Sunday, October 11*

> "How can I know what I think until I see what I say?" --- E. M. Forster on Writing

# Overview 

Your task is to write a short paper on a theme that we have discussed or addressed in this course thus far -- whether in my lectures, our discussions, or your reading.

This assignment has several purposes. First, it is my way of gauging whether you understand the material and are attempting to grapple with the challenges it brings to understanding economics. You are perfectly free to accept it, reject it, or find a way to synthesize it with your current understanding of economic issues and research, so long as you argue why!  Second, it is a chance for you to stimulate and develop your own thinking on some of the issues raised in this course, as well as an opportunity to develop your writing and communication skills. These skills are vital to any profession, and in truth, you do not fully understand an idea unless you engage it in writing. Finally, this assignment will be good preparation for your longer term paper (you could even reuse a topic with appropriate changes).

I am *NOT* looking for a survey of existing research, a series of block quotes showing what economists have said about $x$, a regurgitation of my lectures, a list of pros and cons with a last minute conclusion, a book review, and so on. I also do *NOT* want you to compress *everything* you have learned so far into a single paper. You should only use those insights that you believe are relevant to your topic and your argument. 

I am looking for a paper that is your own take on a topic, and one that puts forth an *argument* and defends it. 

# Length, References, & Mechanics

The required mechanics of this assignment are quite informal. This is not a research paper, nor an op-ed. Imagine it like a conversation among friends about some topic -- it should be reasonably informative and persuasive, but not necessarily a formal piece of writing. I expect you to write **between 3 and 5 pages (double spaced, size 12 Times New Roman or Arial font, 1" margins)**. You do not need to do any original research or use any outside sources aside from our readings, if applicable (if you wish to respond to something we read or if you believe it helps make your point).

I would also like you to reference and occasionally quote from the readings or cite to other scholarly works that reference the works we are discussing. Outside research and references are not required, but may help improve your analysis of whatever you choose to write about. I am not particularly picky about exactly how you format your citations or bibliography, just please be consistent, and do not use footnotes or endnotes (only because they annoy me). I *suggest* the APA author-year-page in-text citation format that is fairly standard in economics journals, i.e.: “The division of labor is limited by the extent of the market,” (Smith 1776: 27). Look at my slides or my handouts for a suggested bibliography style. If you use `.bib` files, the default formatting is fine.

# Grading Rubric

Here is the rubric that I will use to grade your paper:

| Category | Points |
|----------|-------:|
| Soundness | 40 |
| Persuasiveness | 40 |
| Clarity & Organization | 10 |
| References/Quotes | 10 |
| TOTAL | 100 |

- **Economic Soundness**: Does your topic have economic content relevant to the history of economic thought? Do you *accurately* describe the opinions of previous economic writiers? If applicable, do you properly apply modern economic theory? Are your explanations consistent and logical, and did you apply them correctly? Did you choose relevant (and non-cherry picked) evidence to back it up? Are your facts, data, or case studies accurate (if appropriate)? 
- **Persuasiveness:** How persuasive is your argument? Would a reasonably educated college-level reader find themselves understanding and agreeing with you? 
- **Clarity:** How clear is your paper? Does it focus clearly on a particular issue and provide some analysis or explanation of it?
- **References/Quotes:** Do you engage with what the writers we discuss had to say? Do you represent their views correctly? Do you have quotes from the readings that can back up your point? If applicable, do you cite scholarly works interpretting or analyzing the works we have read?

## Potential Topic Prompts

Here are a few **suggestions**, based on trains of thought that I think would be interesting, or ideas that I myself am currently grappling with. You are welcome to use these as motivating questions or jumping-off points to develop your own thoughts on an issue, *just make sure to write a paper that has a reasonably clear thesis and argument.* **Do not think of these as a required set of questions that you must choose and specifically answer (i.e. this is not an exam)**. In fact, each bullet point contains multiple related questions, any one of which might spark a separate interesting paper.

**You are _not_ required to pick one of these questions**. That is, you can write on your own topic that is interesting to you so long as it is relevant and builds off of what we have discussed so far. One suggestion would be to take a discussion question that you turned in or found interesting from the readings and lectures as a jumping off point.

**If you truly want to be efficient, I would consider writing about the theme of your longer term paper, focusing on the idea in this era that we have discussed so far (and do a later era of that theme for your 2nd short paper)!**

1. A lot of mercantilist tropes and policy ideas remain popular today (“Buy American,” our country needs to to “win at trade”,”tariffs protect American workers,” obsessions over the balance of trade and fixing trade deficits, etc.). Why do you think this remains popular in the minds of the people and/or political leaders? Why do you think some such policies are still in existance?

2. How much does “the Ricardian vice” still persist among economists who focus on abstract theoretical models with simplifying assumptions at the potential expense of real world evidence? Is this a fair or unfair characterization?

3. Ending mercantilism is simple, in theory: get rid of trade barriers, monopoly privileges, and other restrictions. Why is it so hard? And in particular, should we encourage developing countries to do this?

4. How did Europe escape feudalism? Is Adam Smith’s narrative in Book III of the *Weath of Nations* convicing? What remnants of feudal ideas, institutions, and customs remain today?

5. What are the major similarities and differences between Hume and Smith’s theories of moral sentiments? How do they compare to other moral theories (like Kantian deontology or utilitarianism and consequentialism)? What do you find convincing or unconvincing?

6. Grapple with *Das Adam Smith problem*: is there consistency or inconsistency between Smith’s *Theory of Moral Sentiments* and *The Wealth of Nations*?

7. How much of Ricardo’s theoretical system was influenced by the Corn Laws? Do you think Ricardo would have gone about his model differently if there were not policies raising Corn prices and rents at the time?

8. While they clearly agreed agriculture experienced diminishing returns, the classical economists more vaguely thought manufacturing did not (perhaps it was constant returns, perhaps it was increasing returns). How might they have made a Smithean division-of-labor argument defending increasing returns to manufacturing (or to the economy in general)? 

9. What is “capital” to the classical economists, and how does that comport with what we think about “capital” in economics today? What is the difference between “profit” and “interest”, between “capitalist” and “entrepreneur?”

10. The classicals, the physiocrats, and Marxists clearly believed that some labor is productive, and some labor is unproductive. Why did they think this, why did these groups have such different targets for “unproductive” labor, and do you think this distinction is still valid today?

11. In what way are Ricardian rents and Ricardo’s theory of rent connected with what we call “rent-seeking” behavior in modern economics?

12. What do you make of the debate over Say’s law between Ricardo, the Mills, Say, and Malthus? Was there a clear winner and loser?

13. Ricardo used a highly simplified model of the economy as firm in his Corn model to the distribution of income and consequences of economic growth. In what way is this similar to modern macroeconomic models of the steady state?