---
title: "Short Paper 2"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
```

- *Due Sunday, November 8 (email)*

Your assignment is the same as [short paper 1](/assignment/01-short-paper), so please see that page for details. This page merely consists of new potential topic prompts to guide you.

## Potential Topic Prompts

Here are a few **suggestions**, based on trains of thought that I think would be interesting, or ideas that I myself am currently grappling with. You are welcome to use these as motivating questions or jumping-off points to develop your own thoughts on an issue, *just make sure to write a paper that has a reasonably clear thesis and argument.* **Do not think of these as a required set of questions that you must choose and specifically answer (i.e. this is not an exam)**. In fact, each bullet point contains multiple related questions, any one of which might spark a separate interesting paper.

**You are _not_ required to pick one of these questions**. That is, you can write on your own topic that is interesting to you so long as it is relevant and builds off of what we have discussed so far. One suggestion would be to take a discussion question that you turned in or found interesting from the readings and lectures as a jumping off point.

**If you truly want to be efficient, I would consider writing about the theme of your longer term paper, focusing on the idea in this era that we have discussed so far (and do a later era of that theme for your 2nd short paper)!**

1. Does the marginalist approach improve on the value & price theories of the classical economists?

2. What exactly is “utility”? What are the consequences of treating it as a measurable, cardinal thing, versus an unmeasurable, ordinal tool for building theories of demand and price?

3. Are factors of production paid their marginal product in reality? What implications does this have for a theory of competitive markets and factor pricing (marginal productivity theory)? 

4. If marginal productivity theory were *true*, even if only under certain circumstances or tendencies, does that mean that market outcomes and the distribution of income is *morally justified*, as Clark suggested?

5. What is the relationship between increasing returns to scale and competitive markets (or lack thereof)?

6. What is capital?

7. What is interest?

8. Bohm-Bawerk suggested that a proper understanding of time, interest, and capital clearly demolishes Marxist arguments about capitalists exploiting workers. Do you agree?

9. How mathematical should economic analysis be? Consider the ideas and influence of Cournot, Marshall, Edgeworth, and Pareto, among others.

10. How much of modern economics is Marshallian? Or in what ways did Marshall lead economists astray on certain ideas?