---
title: "Term Paper"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
```

*Due by email by 11:59 PM Sunday, November 22*

> "How can I know what I think until I see what I say?" --- E. M. Forster on Writing

# Overview

Your task is to write a term paper on a theme in the history of economic thought. You should either focus on one idea, concept, or issue and trace its evolution from pre-classical to modern economic writings on the subject (while critically appraising the trajectory), *or* you may analyze a particular era or debate that you find interesting. In committing to either path, you should engage the key texts from the famous writers that constitute our readings, as well as some outside readings and research to provide further analysis and ground your arguments.

Although it is only a sample size of 1, I suggest you look at my term paper from my undergraduate history of economic thought course as an example of the latter type of paper (focusing primarily on the debate between Malthus/Keynes and Ricardo/Say, so two primary time periods):

- [<i class="fas fa-file-pdf"></i> Safner (2010), “The Duality of Say’s Law: A Restoration of J.B. Say’s Original Intentions”](/readings/Safner-2010.pdf)

Rather than a series of exams, a term paper in a 400-level seminar course pushes you to grapple with the famous writings and controversies of the economics profession, serving as part of your capstone in economics. This is also my way of gauging whether you understand the material and are attempting to grapple with the challenges it brings to understanding economics. Second, it is a chance for you to stimulate and develop your own thinking on some of the issues raised in this course, as well as an opportunity to develop your writing and communication skills. These skills are vital to any profession, and in truth, you do not fully understand an idea unless you engage it in writing.

I am *NOT* looking for a survey of existing research, a series of block quotes showing what economists have said about $x$, a regurgitation of my lectures, a list of pros and cons with a last minute conclusion, a book review, and so on. I also do *NOT* want you to compress *everything* you have learned so far into a single paper. You should only use those insights that you believe are relevant to your topic and your argument. 

I am looking for a paper that is your own take on a topic, and one that puts forth an *argument* and defends it, in the context of the history of economic thought.

# Length, References, & Mechanics

As a 400-level term paper, I expect approximately $\mathbf{15 \pm 5}$ pages (the usual double-spaced, size 12 font, 1 inch margins). You will need space to develop your arguments, place the readings in context, and connect it with modern research on the topic.

You should cite the texts of the authors we have read (if useful, you can cite them as chapters in the Warren and Samuels *Reader*). Be aware that the *excerpts* of the works contained in the reader may not be the only thing the author has written about that will be relevant to your topic. Thus, it will often be necessary to find full copies of some of the necessary works. Fortunately, most of the famous books (Smith, Ricardo, Malthus, Marx, Marshall, etc) can be found free online, at websites like the [Library of Economics and Liberty](https://www.econlib.org/books/), [Liberty Fund](https://oll.libertyfund.org/), or [Project Gutenberg](https://www.gutenberg.org/). You should not have to buy additional books for this paper.

I would also like you to use scholarly references, that is, articles from economics journals and cite them properly. I do not have a minimum requirement of the amount of references, but I expect you to have *at least* 3-5, depending on your paper topic and thesis. 

I am not particularly picky about exactly how you format your citations or bibliography, just please be consistent, and do not use footnotes or endnotes for references (only because I find them annoying). I *suggest* the APA author-year-page in-text citation format that is fairly standard in economics journals, i.e.: “The division of labor is limited by the extent of the market,” (Smith 1776: 27). 

Look at my slides or my handouts for a suggested bibliography style. If you use `.bib` files, the default formatting is fine.

# Grading Rubric and Deadlines

This paper is **due by email to me by 11:59 PM Sunday November 22**. Afterwards, I will deduct 1 point for every hour it is late.

While it may be possible for many papers in your college career (and worked for me), this not a paper you can easily write in the last minute and do well on. To ensure that you do not get too far behind, I have split the assignment into stages that are due at different intervals over the semester. Note that your topic can and may change depending on what you are able to find and work with.

I *highly, highly suggest* that you strategically use the short paper assignments as waypoints for this term paper. In other words, write your short paper 1 about what the Classical economists thought about your theme, and write short paper 2 about what the Neoclassical economists thought about your theme.

Here is the rubric that I will use to grade your paper:

| Category | Points |
|----------|-------:|
| Soundness | 35 |
| Persuasiveness | 35 |
| Clarity | 10 |
| Organization | 10 |
| References/Quotes | 10 |
| TOTAL | 100 |

- **Economic Soundness**: Does your topic have economic content relevant to the history of economic thought? Do you *accurately* describe the opinions of previous economic writiers? If applicable, do you properly apply modern economic theory? Are your explanations consistent and logical, and did you apply them correctly? Did you choose relevant (and non-cherry picked) evidence to back it up? Are your facts, data, or case studies accurate (if appropriate)? 
- **Persuasiveness:** How persuasive is your argument? Would a reasonably educated college-level reader find themselves understanding and agreeing with you? [Write for an audience wider than just members of this class. Therefore, don't use terms, sources, or "inside jokes" that only your classmates in this class (and no one else) would understand.] Remember, your goal is not to convince *me* (though you may), your goal is to convince *any educated reader*, and I grade you the probability that this is likely. You are the lawyer, I am the judge, and your audience is the jury.
- **Clarity:** How clear is your paper? Is it clear what your thesis is, focusing on a particular theme, and providing a relevant narrative?
- **Organization:** Is your paper organized? Have you presented your separate arguments/examples in a logical order? Is it clear when you are moving on from one section to another? Is it clear when and where you are summarizing and concluding?
- **References/Quotes:** Do you engage with what the writers we discuss had to say? Do you represent their views correctly? Do you have quotes from the readings that can back up your point? Do you cite scholarly works interpretting or analyzing the works we have read? Do you give proper attribution and use a consistent citation practice?

# A Few Suggested Themes

Here are a few themes that you might consider tracing the evolution of writing on:

- Models of market competition (must it be “perfect”?, normative vs. positive views of competition)
- Income or wealth (in)equality (by sex, race, class, etc.)
- The environment
- Monopolies and competition policy/antitrust
- Increasing returns^[I’m writing a paper on the history of this now.]
- Innovation, innovation policy, intellectual property rights^[This sounds like another good paper I’d write if I had time!]
- Economics of sex/gender, women’s rights
- Slavery, racism, eugenics
- Rationality vs. irrationality
- Role of institutions vs. pure *homo-economicus*
- Socialism as an alternative to markets/capitalism
- Proper role of government
- Economic growth
- Moral (un)desirability of economic growth, consumerism
- Harmony vs. conflict in society
- Methodology in economics
  - Use of formal mathematics in theory
  - Inductive vs. deductive reasoning
  - Theory vs. econometrics & empirical work

Note that some may require some additional outside research, and modern readings to supplement what the early writers discussed (or did not discuss).